site_name: cest->framework();
copyright: Copyright &copy; 2018 - 2024 César González Segura - Cest is MIT licensed
repo_url: https://github.com/cegonse/cest
edit_uri: ""
repo_name: cegonse/cest
nav:
  - Home: index.md
  - Quickstart:
    - Writing your first test: quickstart/first.md
    - Using Cest Runner: quickstart/runner.md
    - Integrating with CMake: quickstart/cmake.md
    - Testing C code: quickstart/bare_c.md
  - API Reference: reference.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  features:
    - header.autohide
    - content.code.annotate
  logo: assets/logo.png
  favicon: images/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
        primary: deep purple
        accent: light blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        primary: deep purple
        accent: light blue
  name: material
  highlightjs: true
  hljs_languages:
    - cpp
    - c
    - make
    - cmake
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/cesar-gonzalez-segura
    - icon: material/email
      link: mailto:contact@cesargonzalez.dev
    - icon: fontawesome/brands/telegram
      link: https://t.me/cegonse
    - icon: fontawesome/brands/github
      link: https://github.com/cegonse
